version: '2'

services:

  calculator:
    build:
      context: calculator/
    ports:
      - "8080:8080"
    networks:
      - elk
    depends_on:
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "25826:25826"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana: 
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge