Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.hostname = "golang.dev"

    config.vm.network "private_network", ip: "55.55.55.5"

    config.vm.provision "file", source: "calculator.go", destination: "$HOME/calculator.go"
    config.vm.provision "file", source: "microservice.sh", destination: "$HOME/microservice.sh"

    config.vm.provision :shell, :path => "install.sh"
end 