node {
    stage('preparation') {
        git branch: 'master', 
        credentialsId: 'git-credentials',
        url: 'https://github.com/CarlosAsrc/devops-labs'   
    }

    stage('run-stress-test') {
        dir("gatling-stress-test") {
            sh "sbt gatling:test"
        }
    }
}