Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.box = "bento/ubuntu-18.04"

    config.vm.hostname = "golang.dev"

    config.vm.network "private_network", ip: "55.55.55.5"

    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.install_mode = "pip"
        ansible.version = "2.8.2"
    end
end 