node {
    stage('preparation') {
        git branch: 'master', 
        credentialsId: 'git_credentials',
        url: 'https://github.com/CarlosAsrc/devops-labs'   
    }

    stage ("Provision") {
        dir("vault-provision/ansible_jenkins_provision") {
            ansiblePlaybook playbook: 'playbook.yml', vaultCredentialsId: 'vault_password', credentialsId: 'system_credentials'
        }
    }
}