node {
    stage('preparation') {
        git branch: 'master', 
        credentialsId: 'git-credentials',
        url: 'https://github.com/CarlosAsrc/devops-labs'   
    }
    
    stage('deploy') {
        dir("kubernetes-minikube") {
            withKubeConfig([credentialsId: 'kubernetes-certificate', serverUrl: 'https://192.168.99.100:8443']) {
                sh 'kubectl apply -f kubernetes-deploy/'
            }
        }
    }
}
